
[build]
    base = "resume/"
    publish = "resume/build/"
    command = "yarn build"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[context.production]
    command = "yarn build"