[build]
    base = "client/"
    publish = "client/build/"
    command = "NODE_ENV=staging yarn build"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[context.production]
    command = "yarn build"